#!/usr/bin/env bash
# Install the learning system for Hermes Agent (run on the machine where `hermes gateway` runs).
#
#   ./integrations/hermes/install.sh [--language ru] [--timezone Europe/Moscow] [--home ~/learning] [--rich]
#
#   --rich  tell the skills your Telegram bot uses rich messages (LaTeX, tables, task lists, <details>).
#           You must ALSO enable it in Hermes (see the note printed at the end).
#
# Does four things, all idempotent (safe to re-run after `git pull`):
#   1. links scripts/learn.py as `learn` into ~/.local/bin
#   2. initialises the data directory (progress lives there, NOT in this repo)
#   3. copies the skills into $HERMES_HOME/skills (default ~/.hermes/skills)
#   4. writes the no-LLM reminder script into $HERMES_HOME/scripts
# It prints the two Hermes commands you still run yourself (cron + gateway).
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
LEARN_HOME="${LEARN_HOME:-$HOME/learning}"
LANGUAGE="ru"
TZ_NAME=""
RICH=0

while [ $# -gt 0 ]; do
  case "$1" in
    --language) LANGUAGE="$2"; shift 2 ;;
    --timezone) TZ_NAME="$2"; shift 2 ;;
    --home)     LEARN_HOME="$2"; shift 2 ;;
    --rich)     RICH=1; shift ;;
    -h|--help)  sed -n '2,16p' "$0"; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

command -v python3 >/dev/null || { echo "python3 is required" >&2; exit 1; }

# 1. CLI on PATH
mkdir -p "$HOME/.local/bin"
ln -sf "$REPO/scripts/learn.py" "$HOME/.local/bin/learn"
chmod +x "$REPO/scripts/learn.py"
echo "✔ learn -> $HOME/.local/bin/learn"
case ":$PATH:" in *":$HOME/.local/bin:"*) ;; *) echo "  note: add $HOME/.local/bin to PATH" ;; esac

# 2. data dir
init_args=(--home "$LEARN_HOME" --language "$LANGUAGE")
[ -n "$TZ_NAME" ] && init_args+=(--timezone "$TZ_NAME")
[ "$RICH" = 1 ] && init_args+=(--chat-format rich)
python3 "$REPO/scripts/learn.py" init "${init_args[@]}"

# 3. skills
mkdir -p "$HERMES_HOME/skills"
for s in teach visualize study-plan daily-lesson; do
  rm -rf "$HERMES_HOME/skills/$s"
  cp -R "$REPO/skills/$s" "$HERMES_HOME/skills/$s"
done
echo "✔ skills copied to $HERMES_HOME/skills (teach, visualize, study-plan, daily-lesson)"

# 4. reminder script for `hermes cron create --no-agent` (scripts must live in $HERMES_HOME/scripts)
mkdir -p "$HERMES_HOME/scripts"
cat > "$HERMES_HOME/scripts/learn-nudge.sh" <<SCRIPT
#!/bin/sh
# Generated by integrations/hermes/install.sh — prints today's reminder; empty output = stay silent.
exec env LEARN_HOME="$LEARN_HOME" python3 "$REPO/scripts/learn.py" nudge "\$@"
SCRIPT
chmod +x "$HERMES_HOME/scripts/learn-nudge.sh"
echo "✔ reminder script: $HERMES_HOME/scripts/learn-nudge.sh"

cat <<NEXT

Next (once):
  # daily reminder at 09:00, delivered to your Telegram home channel, zero LLM cost
  hermes cron create "0 9 * * 1-6" --no-agent --script learn-nudge.sh --deliver telegram --name learn-nudge

  # make sure the gateway runs (cron fires inside it)
  hermes gateway status || hermes gateway start

Then, in Telegram, tell your bot:  "Хочу выучить <тема>"  (it will use /study-plan)
and later each day:               /daily-lesson

Guide: $REPO/docs/hermes-telegram.md
NEXT
if [ "$RICH" = 1 ]; then cat <<RICHNOTE

Rich messages: add to $HERMES_HOME/config.yaml (key per Hermes' Telegram docs; check your version), then restart the gateway:
  gateway:
    platforms:
      telegram:
        extra:
          rich_messages: true
Without this the bot would send LaTeX/tables as raw symbols. To go back:  learn config chat_format plain
RICHNOTE
else cat <<RICHNOTE

Optional: Telegram rich messages (LaTeX, tables, task lists, hints) — enable in Hermes, then run:  learn config chat_format rich
RICHNOTE
fi
